# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure 
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

  config.vm.define :namenode do |config|
    config.vm.box = "generic/debian11"
    config.vm.hostname = "namenode"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024  # Set RAM to 1 GB (adjust as needed)
      v.cpus = 1       # Set CPU cores to 1 (adjust as needed)
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "namenode.yml"
    end
  end

  [ "datanode1", "datanode2" ].to_enum.with_index(1).each do |host, i|
    config.vm.define "#{host}" do |config|
      config.vm.box = "generic/debian11"
      config.vm.hostname = "#{host}"
      config.vm.network "private_network", ip: "192.168.56.1#{i}"
      config.vm.provider "virtualbox" do |v|
        v.memory = 1024  # Set RAM to 1 GB (adjust as needed)
        v.cpus = 1       # Set CPU cores to 1 (adjust as needed)
      end
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "datanode.yml"
      end
    end
  end
end